- Simulator/Connections/NG911/Connections911.h
- Simulator/Connections/Neuro/ConnGrowth.h
- Simulator/Connections/Neuro/ConnStatic.h
- Simulator/Core/CPUModel.h
- Simulator/Core/GPUModel.h
- Simulator/Edges/AllEdges.h
- Simulator/Edges/NG911/All911Edges.h
- Simulator/Edges/Neuro/AllDSSynapses.h
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses.h
- Simulator/Edges/Neuro/AllNeuroEdges.h
- Simulator/Edges/Neuro/AllSTDPSynapses.h
- Simulator/Edges/Neuro/AllSpikingSynapses.h
- Simulator/Layouts/NG911/Layout911.h
- Simulator/Layouts/Neuro/DynamicLayout.h
- Simulator/Layouts/Neuro/FixedLayout.h
- Simulator/Recorders/Hdf5GrowthRecorder.h
- Simulator/Recorders/Hdf5Recorder.h
- Simulator/Recorders/Xml911Recorder.h
- Simulator/Recorders/XmlGrowthRecorder.h
- Simulator/Recorders/XmlRecorder.h
- Simulator/Utils/Matrix/SparseMatrix.h
- Simulator/Vertices/AllVertices.h
- Simulator/Vertices/NG911/All911Vertices.h
- Simulator/Vertices/Neuro/AllIFNeurons.h
- Simulator/Vertices/Neuro/AllIZHNeurons.h
- Simulator/Vertices/Neuro/AllLIFNeurons.h
- Simulator/Vertices/Neuro/AllSpikingNeurons.h
Not sure if I got them all since your last merge happened in the middle of me adding this, but this is at least most of them (I also fixed some spacing in the comments where I saw it)
Fixes #156
> Added override tags on subclass methods

- Simulator/Core/Driver.cpp
- Simulator/Core/Simulator.cpp
- Simulator/Core/Simulator.h
- Simulator/Recorders/Hdf5Recorder.cpp
- Simulator/Recorders/Hdf5Recorder.h
- Simulator/Recorders/NG911/Xml911Recorder.cpp
- Simulator/Recorders/Neuro/Hdf5GrowthRecorder.cpp
- Simulator/Recorders/Neuro/XmlGrowthRecorder.cpp
- Simulator/Recorders/Neuro/XmlSTDPRecorder.cpp
- Simulator/Recorders/XmlRecorder.cpp
- Simulator/Recorders/XmlRecorder.h
- Testing/Core/SimulatorTests.cpp
resultFileName is now instantiated inside constructor for XmlRecorder & Hdf5Recorder (will later move to superclass). stateOut_ renamed to resultOut_.
> Removed command line parameters for result filename.

- docs/Developer/CMakeListsCuda.md
- docs/index.md
Added documentation for what I learned about using CUDA with CMakeLists for GPU sims
> Cmakelists dev documentation additions

- docs/NeuroImplementation.md
Fixes broken image links that resulted from the recent file reorganization.
> Fixed broken image links due to files reorganization

- docs/Developer/codingConventions.md
- docs/Developer/eventBuffering.md
- docs/Developer/index.md
- docs/NeuroImplementation.md
- docs/index.md
Refactored the documentation from the Graphitti repo. This pull request addresses the issue #181 
Merging this PR with master separates documentation changes done in PR #281.
> Refactor :: graphitti-documentation

- .github/workflows/publish-gh-pages.yml
- docs/Developer/GHActions.md
- docs/Developer/GHPages.md
Made a manual publish workflow action for gh-pages. Unfortunately, in order to test this properly a PR must be created.
> Created workflow to manually publish gh-pages

- Simulator/Connections/Neuro/ConnGrowth.cpp
- Simulator/Connections/Neuro/ConnGrowth_d.cu
- Simulator/Recorders/Hdf5Recorder.cpp
- Simulator/Recorders/Hdf5Recorder.h
- Simulator/Recorders/IRecorder.h
- Simulator/Recorders/XmlRecorder.cpp
- Simulator/Recorders/XmlRecorder.h
- Simulator/Vertices/EventBuffer.cpp
- Simulator/Vertices/EventBuffer.h
- Simulator/Vertices/Neuro/AllIFNeurons.cpp
- Simulator/Vertices/Neuro/AllIFNeurons_d.cu
- Simulator/Vertices/Neuro/AllIZHNeurons.cpp
- Simulator/Vertices/Neuro/AllIZHNeurons.h
- Simulator/Vertices/Neuro/AllLIFNeurons.cpp
- Simulator/Vertices/Neuro/AllLIFNeurons.h
- Simulator/Vertices/Neuro/AllSpikingNeurons.cpp
- Simulator/Vertices/Neuro/AllSpikingNeurons.h
This pull request has `Event Buffer` changes( new vector based data structure to eliminate dynamic array implementation).
It also has changes in impacted Vertex classes and Recorder classes  by introducing Event Buffer.
Changes are tested with Manually by taking  different simulation instances and comparing the output. 
```
test-medium-2.xml
test-small-911.xml
test-small.xml
test-tiny-stdp.xml
test-medium-stdp.xml
test-small-connected.xml
test-tiny.xml
```
>  Event Buffer and changes from the impacted classes

- docs/Developer/eventBuffering.md
Drafted first version of documentation for Event Buffer data structure implementation
> documentation :: Refactor :: EventBuffer.md

- .github/workflows/format.yml
- README.md
- Simulator/Core/Simulator.h
I created a GitHub action to automatically run clang-format during push and pull requests whenever a .cpp or .h file is included. This action has been tested on a separate fork of Graphitti so it should work straight away.
> Created automated format checking script

- Simulator/Vertices/AllVertices.cpp
- Simulator/Vertices/Neuro/AllIFNeurons_d.cu
Fixes #333
Fixes the segmentation fault at the end of GPU simulations. See conversation in issue #333 for more details.
> Removed assignment of device pointer to host pointer that caused segmentation fault

- Simulator/Edges/Neuro/AllSTDPSynapses.cpp
> Refactored ULONG_MAX to numeric_limits<unsigned long>::max()

- Simulator/Core/GPUModel.cpp
This PR contains the fix for the build error in GPU simulation that had caused because of the an old PR #379
>  PP :: master build error fix

- docs/Developer/codingConventions.md
- docs/Developer/cppStyleGuide.md
Fix issue #399   
Added documentation for const and constexpr.
Fixed the existing coding style.
> Documentation for new features

- Simulator/Core/Simulator.cpp
- Simulator/Core/Simulator.h
- build/RuntimeFiles/log4cplus_configure.ini
Add the workbench logger to output a log file for workbench use
> Work bench log

- docs/Developer/codingConventions.md
- docs/Developer/cppStyleGuide.md
- docs/index.md
This PR documents the following cpp features:
1. Copy and Move operations
2. Smart Pointers
3. Aliases
4. Inputs and Outputs
This is a fix for issue #399 and extension of PR [#400](https://github.com/UWB-Biocomputing/Graphitti/pull/400)
> Document cpp features

- Simulator/Edges/Neuro/AllNeuroEdges.h
- Simulator/Edges/Neuro/AllSpikingSynapses.h
- Simulator/Utils/BGTypes.h
- Simulator/Utils/Global.h
- Simulator/Utils/GraphManager.h
- Simulator/Utils/InputManager.h
- Simulator/Utils/RNG/MersenneTwister_d.h
- docs/Testing/ArrayPerformance/ArraySpeedTest.cpp
- docs/Testing/CastingTest/CastingTest.cpp
Closes Issue #424 
Replaced `typedef` with the `using` keyword in the Graphitti codebase as it provides a more consistent syntax with the rest of the code and works well with templates.
> [Issue 424] Replace typedef keyword with using keyword

- docs/Testing/ArrayPerformance/ArrayPerformance.md
- Added 3 tables to the performance.md : Initialization, Access and Sum, and Random Access and Sum.
- If you prefer a different format or have any specific requirements, please let me know.
> [Issue 454] Updated ArrayPerformance.md

- Contributors.md
Closes #461 
This PR adds the Contributors.txt file with all students' names.
> [ISSUE-461] Create a Contributors.txt file

- Contributors.md
Closes #470 
This PR adds Andrzej Dawiec to the Contributors.md file
> [ISSUE-470] Add Andrzej Dawiec to the Contributors.md file 

- Contributors.md
Closes #475 
This PR Revises Contributors.md and adds Andrzej Dawiec to Undergraduate section
> [ISSUE 475] Add Andrzej Dawiec to Contributors.md Revision 

- .github/workflows/format.yml
- .github/workflows/tests.yml
Changed `development-1h23` to `development` in two `.yml` files.
> hotfix: Changed development branch name

- Tools/graphMLVis/visualize_graphML.py
> Issue 548 visualizer file loader

- .github/workflows/plantUML.yml
Closes #601 
Changed the plantuml generation reference from the old (and deleted) repo to the forked repo in UWB-Biocomputing.
> [ISSUE-601] Hotfix puml action

- Simulator/Connections/Neuro/ConnGrowth.cpp
- Simulator/Connections/Neuro/ConnStatic.cpp
- Simulator/Core/EdgeIndexMap.h
- Simulator/Layouts/Layout.h
- Simulator/Layouts/Neuro/DynamicLayout.h
- Simulator/Layouts/Neuro/FixedLayout.h
- Simulator/Recorders/Recordable.h
- Simulator/Recorders/RecordableBase.h
- Simulator/Vertices/AllVertices.h
- Simulator/Vertices/EventBuffer.h
- Simulator/Vertices/Neuro/AllIFNeurons.h
- Simulator/Vertices/Neuro/AllIZHNeurons.h
- Simulator/Vertices/Neuro/AllLIFNeurons.h
- Simulator/Vertices/Neuro/AllSpikingNeurons.h
Closes #571 
Implemented serialize functions for all Neuro-related classes in `Layout` and `AllVertices`, along with their utility classes.
Classes Targeted:
1. Layout, FixedLayout, DynamicLayout
2. AllVertices, AllSpikingNeurons, AllIFNeurons, AllLIFNeurons, AllIZHNeurons
3. EventBuffer, Recordable, RecordableBase
> [ISSUE-571] Serialize Layout and AllVertices Classes

- .github/pull_request_template.md
Closes #628 
This PR adds a PR template for Graphitti
> [ISSUE-628] Create pull_request_template.md

- Simulator/Connections/Connections.cpp
- Simulator/Core/Model.cpp
- Simulator/Core/Simulator.cpp
- Simulator/Layouts/Layout.cpp
Closes #270 
Since Google Test acts up when we test for an exit. We will keep factory returning nullptr, but each class that uses the factory will check for nullptr, and will exit the program if that is the case.
> [ISSUE 270] Handle Nullptr From Factory

- Simulator/Connections/Neuro/ConnGrowth.cpp
- Simulator/Connections/Neuro/ConnGrowth.h
- Simulator/Vertices/EventBuffer.cpp
- Simulator/Vertices/Neuro/AllSpikingNeurons_d.cpp
> [release-v0.9.3] Fixed the EventBuffer bug

- .github/pull_request_template.md
Closes #695 
Updated the PR template to reflect the correct GPU Test.
> [ISSUE-695] Update pull_request_template.md

- Simulator/Connections/Connections.h
- Simulator/Core/Model.h
- Simulator/Edges/AllEdges.h
- Simulator/Layouts/Layout.h
- Simulator/Vertices/AllVertices.h
Closes #706 
Removed the versioning logic from individual base classes - `AllEdges`, `Layout`, `AllVertices`, `Connections`; into the `Model` class. This change simplifies the versioning structure by maintaining version info only in the `Model` class, which is the starting point of the serialization and deserialization.
> [ISSUE_706] Moved Versioning Info from Base Classes to Model Class

- Contributors.md
Closes #710 
Add Vanessa Arndorfer to the Contributors.md file as part of the lab onboarding process
> [ISSUE-710] Added Vanessa Arndorfer to the Contributors.md file

- Contributors.md
> [ISSUE-671] Add <Hari Priya Dhanasekaran> to the Contributors.txt file.

- Tools/InputGeneration/README.md
- docs/Developer/GraphAndEventInputs.md
> Update Documentation: XML files and hyperlink

- Tools/graphMLVis/visualize_graphML.py
> Issue 518 visualizer tabular view

- .github/workflows/format.yml
- .github/workflows/tests.yml
So, all tests will run for any PR.
Closes #756 
Changed the two testing actions to trigger on type of PR activity, rather than only the master and development base branches.
> [hotfix-issue-756] Change test actions to work on any PR

- Tools/InputGeneration/ClusterPointProcess/cluster_point_process.py
- Tools/InputGeneration/ClusterPointProcess/cluster_point_process_functions.py
Closes #768 
Changes in comments
- [Check] Added Documentation
> [ISSUE-768] Update comments for 911 input generation code

- Simulator/Core/GPUModel.cpp
- Simulator/Core/GPUModel.h
- Simulator/Core/OperationManager.cpp
- Simulator/Core/Operations.h
- Simulator/Edges/AllEdges.cpp
- Simulator/Edges/AllEdges.h
- Simulator/Edges/NG911/All911Edges.h
- Simulator/Edges/Neuro/AllDSSynapses.h
- Simulator/Edges/Neuro/AllDSSynapses_d.cpp
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses.h
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses_d.cpp
- Simulator/Edges/Neuro/AllSTDPSynapses.h
- Simulator/Edges/Neuro/AllSTDPSynapses_d.cpp
- Simulator/Edges/Neuro/AllSpikingSynapses.h
- Simulator/Edges/Neuro/AllSpikingSynapses_d.cpp
- Simulator/Vertices/AllVertices.cpp
- Simulator/Vertices/AllVertices.h
- Simulator/Vertices/NG911/All911Vertices.h
- Simulator/Vertices/Neuro/AllIFNeurons.h
- Simulator/Vertices/Neuro/AllIFNeurons_d.cpp
- Simulator/Vertices/Neuro/AllIZHNeurons.h
- Simulator/Vertices/Neuro/AllIZHNeurons_d.cpp
> Issue 828 allocate op

- Simulator/Core/GPUModel.cpp
- Simulator/Core/GPUModel.h
- Simulator/Core/Serializer.cpp
- Simulator/Edges/AllEdges.cpp
- Simulator/Edges/AllEdges.h
- Simulator/Edges/NG911/All911Edges.h
- Simulator/Edges/Neuro/AllDSSynapses.h
- Simulator/Edges/Neuro/AllDSSynapses_d.cpp
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses.h
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses_d.cpp
- Simulator/Edges/Neuro/AllSTDPSynapses.h
- Simulator/Edges/Neuro/AllSTDPSynapses_d.cpp
- Simulator/Edges/Neuro/AllSpikingSynapses.h
- Simulator/Edges/Neuro/AllSpikingSynapses_d.cpp
- Simulator/Vertices/AllVertices.cpp
- Simulator/Vertices/AllVertices.h
- Simulator/Vertices/NG911/All911Vertices.h
- Simulator/Vertices/Neuro/AllIFNeurons.h
- Simulator/Vertices/Neuro/AllIFNeurons_d.cpp
- Simulator/Vertices/Neuro/AllIZHNeurons.h
- Simulator/Vertices/Neuro/AllIZHNeurons_d.cpp
- Simulator/Vertices/Neuro/AllSpikingNeurons.h
- Simulator/Vertices/Neuro/AllSpikingNeurons_d.cpp
Closes #
Refactored multiple GPU-related methods (e.g., `copyToDevice`, `copyToGPU`, and `copySynapseIndexMapHostToDevice`) across neuron and synapse classes to remove parameter dependencies. These changes allow the functions to be registered directly with the centralized `OperationManager`.
This transition from chained execution to centralized registration improves modularity and maintains a single point of control for GPU operations, aligning with the design of a more unified and extensible operation dispatch system.
> Issue 833 copy from gpu

- CMakeLists.txt
- Simulator/Utils/DeviceVector.h
- Simulator/Vertices/Neuro/AllIFNeurons.h
- Simulator/Vertices/Neuro/AllIFNeurons_d.cpp
- Simulator/Vertices/Neuro/AllIZHNeurons.h
- Simulator/Vertices/Neuro/AllIZHNeurons_d.cpp
- Simulator/Vertices/Neuro/AllLIFNeurons_d.cpp
- Simulator/Vertices/Neuro/AllSpikingNeurons.h
- Simulator/Vertices/Neuro/AllSpikingNeurons_d.cpp
- Testing/UnitTesting/DeviceVectorTests.cpp
1. DeviceVector.h is added in the Utils and integrated with neural vertex classes. It is conditionally compiled on the basis of __CUDACC__ macros defined by nvcc. 
2. Structures are basically empty now except it still holds only event buffer for the device code.
3. Each kernel takes explicit parameter.
5. Units tests are also added which tests both CPU and GPU functionality for device vector.
> Device Vector added and Integrated with Neuro Vertices
