- Simulator/Connections/Connections.cpp
- Simulator/Edges/AllEdges.cpp
- Simulator/Edges/AllEdges.h
- Simulator/Edges/Neuro/AllSTDPSynapses.h
- Simulator/Edges/Neuro/AllSpikingSynapses.cpp
Proposed fix for EdgeIndexMap creation, addresses issues #188, #199
Does not switch to `valarrays` or `vectors`, that can be done independently later.
Allocates some more memory than it used to, but shouldn't affect how it works.
It used to allocate the minimum required space, now allocates space for `numVertices * maxEdgesPerVertex` edges.
> EdgeIndexMap Fix

- Simulator/Recorders/Hdf5Recorder.cpp
- Simulator/Recorders/Hdf5Recorder.h
- Simulator/Recorders/XmlRecorder.cpp
Added checks to XMLRecorder & HDF5Recoder to ensure that we have write permissions for output file before beginning simulation.
> Outputfile verify issue 50

- .github/workflows/gh-pages.yml
Implements #185 
Closes #253 
This Github Action auto-generates the project's Doxygen documentation and deploys it to an orphan gh-pages branch.
The idea is that we can set the docs directory in gh-pages branch as the root for our documentation page: https://uwb-biocomputing.github.io/Graphitti/
Does it make sense to have it executing on every push and pull requests to the master branch?
> Created Github Action to auto-generate Doxygen documentation and deploys it to gh-pages branch.

- .github/workflows/publish-gh-pages.yml
- docs/Developer/GHActions.md
- docs/Developer/GHPages.md
Manually publishing the gh-pages using the manual-gh-pages.yml action no longer destroys the Doxygen files. Now, all Doxygen files are regenerated during this action. This allows for the gh-pages branch to stay clean and organized without a commit history while also making sure to publish and maintain all relevant documentation and Doxygen files.
> Manually publishing gh-pages no longer destroys Doxygen files

- CMakeLists.txt
- Simulator/Connections/Connections.cpp
- Simulator/Connections/ConnectionsFactory.cpp
- Simulator/Connections/ConnectionsFactory.h
- Simulator/Connections/NG911/Connections911.h
- Simulator/Core/Driver.cpp
- Simulator/Core/Model.cpp
- Simulator/Core/Simulator.cpp
- Simulator/Edges/EdgesFactory.cpp
- Simulator/Edges/EdgesFactory.h
- Simulator/Layouts/Layout.cpp
- Simulator/Layouts/LayoutFactory.cpp
- Simulator/Layouts/LayoutFactory.h
- Simulator/Recorders/RecorderFactory.cpp
- Simulator/Recorders/RecorderFactory.h
- Simulator/Utils/Global.cpp
- Simulator/Utils/Global.h
- Simulator/Utils/RNG/RNGFactory.cpp
- Simulator/Utils/RNG/RNGFactory.h
- Simulator/Vertices/VerticesFactory.cpp
- Simulator/Vertices/VerticesFactory.h
- Testing/Core/ConnectionsFactoryTests.cpp
- Testing/Core/EdgesFactoryTests.cpp
- Testing/Core/LayoutFactoryTests.cpp
- Testing/Core/RNGFactoryTests.cpp
- Testing/Core/RecorderFactoryTests.cpp
- Testing/Core/VerticesFactoryTests.cpp
Closes #361.
I did some cleaned up of the various factory classes. If nothing else, this should improve readability.
Summary:
- Switched to using `find`, instead of looping over the `createFunctions` map.
- Changed `noiseRNG` from a naked pointer to a `shared_ptr`.
- Removed not needed class member pointer to the instance created by the factory.
- Wrote Unit Tests for all factory classes.
- Fixed Segmentation fault on destruction of `Connections911` class (revealed by the unit tests).
> Factory cleanup

- Simulator/Connections/Neuro/ConnGrowth.h
- Simulator/Core/Serializer.cpp
- Simulator/Edges/AllEdges.h
- Testing/Core/SerializationTests.cpp
Closes #387 
This PR adds CEREAL_CLASS_VERSION macro on AllEdges and ConnGrowth class. 
In addition, we also extend the serialization unit test to confirm that the output XML file contains the expected class version.
> [Issue-387] Add CEREAL_CLASS_VERSION macro to the serializable classes

- docs/User/installation.md
For issue 353
1.2.2: "Download a release" hyperlink does nothing as we are already where the link is supposed to direct you to
I added a release page link
1.2.2: "Fork and Clone Graphitti" doesn't take you to a different page
I added a link pointing to the section header
1.2.2.1: Says there are no releases, but on BrainGrid GitHub page there are 5 releases
I deleted 1.2.2.1
1.2.3: Where is CMakeLists.txt located?
I added a link (https://github.com/UWB-Biocomputing/Graphitti/blob/master/CMakeLists.txt)
> Document issue353

- .gitignore
Modified .gitignore file to ignore the generated unit test executables for serialization and deserialization and its output.
Fixes #401
> Update .gitignore to exclude unit test executable

- Simulator/Core/EdgeIndexMap.h
- Simulator/Edges/AllEdges.cpp
- Simulator/Edges/NG911/All911Edges.cpp
- Simulator/Edges/Neuro/AllDSSynapses.cpp
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses.cpp
- Simulator/Edges/Neuro/AllNeuroEdges.cpp
- Simulator/Edges/Neuro/AllSTDPSynapses.cpp
- Simulator/Edges/Neuro/AllSpikingSynapses.cpp
- Simulator/Layouts/Layout.cpp
- Simulator/Recorders/Hdf5Recorder.cpp
- Simulator/Utils/Inputs/SInputPoisson.cpp
- Simulator/Utils/Inputs/SInputRegular.cpp
- Simulator/Vertices/AllVertices.cpp
- Simulator/Vertices/NG911/All911Vertices.cpp
- Simulator/Vertices/Neuro/AllIFNeurons.cpp
- Simulator/Vertices/Neuro/AllIZHNeurons.cpp
- Simulator/Vertices/Neuro/AllSpikingNeurons.cpp
Closes #446 
This PR replaces the usage of `resize` followed by `assign` with a single call to `assign` to initialize a vector with default values. This simplifies the code and makes it more efficient by eliminating the need to resize the vector and then fill in the default values separately.
The changes have been tested on the CPU and GPU with the medium config file.
Thanks @jardiamj for raising this issue
> [ISSUE-446] Refactor vector initialization to use assign instead of resize and assign

- .github/workflows/tests.yml
- build/README.md
Closes #460 
This PR adds:
Added "make -j" to line 18 on README.md
Added line 28 on tests.yml "run: make -j" for GitHub Actions Workflow file, noticed a 2ms time difference on raiju ./tests run with -j option enabled on GPU.
> [ISSUE 460] Enhancing build efficiency with the -j option in the make command 

- Simulator/Connections/NG911/Connections911.cpp
- Simulator/Connections/NG911/Connections911.h
- configfiles/test-king-county-911.xml
- configfiles/test-small-911.xml
Closes #406 
Removes the extra level in the Connections parameter node from the XML config file because it is not needed.
> [issue #406] Removed the unnecessary Connections parameter level from XML config file

- Simulator/Edges/Neuro/AllNeuroEdges.cpp
- Simulator/Edges/Neuro/AllSynapsesDeviceFuncs_d.cpp
Closes #410 
This PR checks to make sure switches on edgeType and makes sure they have default cases, with the ability to expand with throwing exceptions in the future if the switches return 0. In principle, return 0 in switch case if error.
> [ISSUE-410] Check switches on edgeType and make sure they have default cases

- docs/Testing/index.md
Solve issue #487 
- Adds documentation in section 303 in which 'make clean' is mentioned to clear cache before compiling for specific testing.
> [ISSUE 487] Hotfix for clearing cache in section 3 documentation

- Simulator/Edges/NG911/All911Edges.cpp
- Simulator/Edges/NG911/All911Edges.h
- Simulator/Vertices/NG911/All911Vertices.cpp
- Simulator/Vertices/NG911/All911Vertices.h
- configfiles/test-spd-911.xml
Closes #529 
This PR implements call redials using a redial probability parameter provided through the config file.
The implementation assumes that once the caller decides to redial, he will do so immediately and will try until the call is answered by the PSAP.
> [ISSUE 529] Implemented call redials in the NG911 models

- Simulator/Connections/Neuro/ConnGrowth.cpp
- Simulator/Edges/Neuro/AllSynapsesDeviceFuncs_d.cpp
Closes #114 
Fixed bug in updateSynapsesWeightsDevice where a synapse between the same neuron could be created.
> [ISSUE 114] Fixed bug in updateSynapsesWeightsDevice

- Simulator/Edges/NG911/All911Edges.cpp
- Simulator/Vertices/NG911/All911Vertices.cpp
- Simulator/Vertices/NG911/All911Vertices.h
Closes #557 
Made all the class members of All911Vertices private. The Xml911Recorder class was made a friend of All911Vertices because it needs access to some of its internal data structures. Some accessors were also implemented for values needed by the All911Edges class.
> [ISSUE 557] Made all class members of All911Vertices private

- CONTRIBUTING.md
- docs/Developer/GitFlowDiagram.md
- docs/Developer/index.md
- docs/index.md
closes #473 
- Added gitflowdiagram.md file under docs/Developer
- Updated CONTRIBUTING.md to support new file (gitflowdiagram.md)
- Updated CONTRIBUTING.md's broken links and numbering (pull requests, github issues, duplicate steps #s)
- Updated index.md in docs/Developer to support new file (gitflowdiagram.md)
- Updated index.md docs to support new file (gitflowdiagram.md)
> [ISSUE-473] Write up GitFlow documentation; add to or link to contributing guide 

- Simulator/Connections/Neuro/ConnGrowth.cpp
- Simulator/Edges/AllEdges.cpp
- Simulator/Edges/AllEdges.h
- Simulator/Edges/NG911/All911Edges.cpp
- Simulator/Edges/Neuro/AllDSSynapses_d.cpp
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses_d.cpp
- Simulator/Edges/Neuro/AllNeuroEdges.cpp
- Simulator/Edges/Neuro/AllNeuroEdges.h
- Simulator/Edges/Neuro/AllSTDPSynapses_d.cpp
- Simulator/Edges/Neuro/AllSpikingSynapses.cpp
- Simulator/Edges/Neuro/AllSpikingSynapses_d.cpp
- Simulator/Edges/Neuro/AllSynapsesDeviceFuncs_d.cpp
- Simulator/Vertices/Neuro/AllSpikingNeurons.cpp
Closes issue #459
This pull request updates the `inUse` member variable within the `AllEdges` class, shifting from `std::vector<std::unique_ptr<bool>>` to `std::vector<unsigned char>`. The decision to utilize `unsigned char` for storing Boolean values is driven by a focus on significantly enhancing serialization. This enables consistent use of the `serialize` method, thereby streamlining the codebase and eliminating the need for separate `load` and `save` methods in the cereal library.
Opting for `unsigned char` brings about a more memory-efficient solution compared to `int`. Additionally, it distinguishes itself from other member variables that store char.
> [ISSUE-459] Change vector of bool to vector of unsigned char

- Simulator/Edges/NG911/All911Edges.cpp
Fixes #577 
This fixes a bug in checking for available space in the queue. When NG911 vertices pull messages from their incoming edges a check is done to ensure that there is space in the queue, this change ensures that the check doesn't fail.
> Fixed bug in the checking for available space in the queue

- Tools/InputGeneration/ClusterPointProcess/cluster_point_process_functions.py
This PR modifies the time of occurrence of the secondary points of the cluster point process to be their cumulative sum added to the primary event's time of occurrence. Conceptually, an emergency incident starts a homogeneous Poisson process that beggins at that particular time.
> [ISSUE 576] Modified the secondary process in the cluster point process script

- CMakeLists.txt
- Simulator/Connections/Connections.h
- Simulator/Connections/Neuro/ConnGrowth.cpp
- Simulator/Connections/Neuro/ConnGrowth.h
- Simulator/Connections/Neuro/ConnStatic.cpp
- Simulator/Connections/Neuro/ConnStatic.h
- Simulator/Core/EdgeIndexMap.h
- Simulator/Core/Serializer.cpp
- Simulator/Edges/AllEdges.h
- Simulator/Edges/Neuro/AllDSSynapses.h
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses.h
- Simulator/Edges/Neuro/AllNeuroEdges.h
- Simulator/Edges/Neuro/AllSTDPSynapses.h
- Simulator/Edges/Neuro/AllSpikingSynapses.h
- Simulator/Utils/Matrix/CompleteMatrix.h
- Simulator/Utils/Matrix/Matrix.h
- Simulator/Utils/Matrix/VectorMatrix.h
- Simulator/Utils/RNG/MTRand.cpp
- Simulator/Utils/RNG/MTRand.h
- Simulator/Utils/RNG/Norm.h
Closes #572
1. Implemented `serialize` functions for all Neuro-related classes in `Connections` and `AllEdges`, along with their utility classes.
2. Replaced existing `load` and `save` methods with a single `serialize` method.
3. Removed version number tracking from derived classes, retaining it only in the base classes.
Classes Targeted:
1. Connections, ConnStatic, ConnGrowth
2. Core: EdgeIndexMap
3. AllEdges, AllDSSynapses, AllDynamicSTDPSynapses, AllNeuroEdges, AllSTDPSynapses, AllSpikingSynapses
4. Matrix, CompleteMatrix, VectorMatrix
5. MTRand, Norm
> [ISSUE-572] Serialize Connections and AllEdges Classes

- Simulator/Vertices/Neuro/AllSpikingNeurons.h
Closes #621 
This PR addresses the compatibility issue with the `registerSpikeHistoryVariables` function in `AllSpikingNeurons.h`. The function was previously declared under CPU-specific code, causing compilation errors when accessed from GPU code. To resolve this issue, I've moved the function declaration to both CPU and GPU accessible location.
> [ISSUE-621] Fix compatibility issue with 'registerSpikeHistoryVariables' function

- CMakeLists.txt
Closes #594  
This pull request updates the CUDA_STANDARD in `CMakeLists.txt` from 11 to 17 to leverage C++17 features like `std::variant` for GPU programming.
To ensure correctness, the GPU simulation was run for a set of 12 configurations (ranging from small to large) before and after the update on commit [f6320b2 ](https://github.com/UWB-Biocomputing/Graphitti/commit/f6320b2e1ccd74cf49440adc93c4c5201fec1061) on the master branch. The results show no difference in the output, indicating compatibility with the standard 17.
Additional testing may be planned for configurations `test-large-very-long.xml` and `911` for completeness.
> [ISSUE-594] Update CUDA Standard to 17 for C++17 Features

- Simulator/Vertices/EventBuffer.cpp
- Simulator/Vertices/Neuro/AllSpikingNeurons_d.cpp
Closes #606 
This PR addresses a bug related to the event buffer implementation. The issue stemmed from an additional slot in the event buffer, leading to inconsistencies between CPU and GPU implementations. This inconsistency caused unexpected behavior during GPU simulation.
Changes Made:
Removed the additional slot from the event buffer initialization, ensuring consistency between CPU and GPU implementations and enhanced the condition for detecting a full buffer using `numEventsInEpoch_`.
Adjusted the buffer size on the GPU side to match the modified event buffer, ensuring compatibility with the CPU implementation.
> [ISSUE-606] Remove Additional Slot from Event Buffer 

- Simulator/Recorders/XmlRecorder.cpp
- Simulator/Recorders/XmlRecorder.h
fix #629 
There are two small issues that are addressed in the XmlRecorder class
1. Remove the "> 0" condition.
[Link to the code](https://github.com/UWB-Biocomputing/Graphitti/blob/93197dc18cf8bcf213af8b47293774a2ab28e439/Simulator/Recorders/XmlRecorder.h#L168-L170)
2. Replace "double" with "bool".
[Link to the code](https://github.com/UWB-Biocomputing/Graphitti/blob/93197dc18cf8bcf213af8b47293774a2ab28e439/Simulator/Recorders/XmlRecorder.cpp#L129-L130)
> [ISSUE-629] Correct two small errors in the XmlRecorder

- Simulator/Utils/GraphManager.cpp
closes #634 
Removed GraphManager's dependence on ParameterManager in readGraph(). Now ParameterManager is only used when graphFilePath_ has not been defined yet.
> Update GraphManager to fix dependency

- Simulator/Core/Core.cpp
- docs/Developer/StudentSetup.md
- docs/User/quickstart.md
- Renames command line options for stimulusfile (-s), deserializefile(-r) and serializefile(-w)
- Updates the command line option in the documentation under Student Quickstart
- Adds command line option in the documentation under Quickstart
> [ISSUE 376] Rename command line options for stimulusfile (-s), deserializefile(-r) and serializefile(-w)

- Simulator/Connections/Neuro/ConnGrowth.cpp
- Simulator/Recorders/Hdf5Recorder.cpp
- Simulator/Recorders/Hdf5Recorder.h
- Testing/UnitTesting/Hdf5RecorderTests.cpp
Closes #655
I implemented the init() and term() for Hdf5Recorder, but for there are still some problems with the init(), I can't fix it for now
> implement the init() and term() for Hdf5 Recorder

- Simulator/Connections/Neuro/ConnGrowth.cpp
- Simulator/Connections/Neuro/ConnGrowth.h
Closes #675
This adds back the frontier delta computation into the `ConnGrowth` class. The previous removal of this computation caused the simulation results to deviate from the good known results, for long simulations. For example, 46 epochs or more for the `test-medium-connected-long.xml` simulation.
> [ISSUE 675] Added frontier delta computation back into ConnGrowth

- Simulator/Core/Model.cpp
- Simulator/Recorders/Hdf5Recorder.cpp
- Simulator/Recorders/Hdf5Recorder.h
- Simulator/Recorders/NG911/Xml911Recorder.cpp
- Simulator/Recorders/NG911/Xml911Recorder.h
- Simulator/Recorders/Recorder.h
- Simulator/Recorders/XmlRecorder.cpp
- Simulator/Recorders/XmlRecorder.h
- Testing/UnitTesting/Hdf5RecorderTests.cpp
- Testing/UnitTesting/XmlRecorderTests.cpp
Closes #658 
Implement compileHistories() for UpdatedType:: DYNAMIC for Hdf5 Recorder, inside the compileHistories(), in order to allow us to create HDF5 files that hold data that is generated incrementally during the simulation and saved after each simulation epoch, we need to extend the size of the dataset, so I change a way to create a dataset by using chunk, and then using the hyperslab to the extended portion of the dataset, but don't forget to call startNewEpoch at the beginning of each simulation epoch to prepare for recording new events.
> Implement compileHistories() for UpdatedType:: DYNAMI for Hdf5 Recorder

- Simulator/Core/Core.cpp
- Simulator/Vertices/AllVertices.h
- Simulator/Vertices/NG911/All911Vertices.h
- Simulator/Vertices/Neuro/AllSpikingNeurons.cpp
- Simulator/Vertices/Neuro/AllSpikingNeurons.h
Closes #692
This PR refactors the spike history variable registration function, moving it from the `AllSpikingNeurons` class to the `AllVertices` class. Additionally, the function name has been changed from `registerSpikeHistoryVariables` to `registerHistoryVariables` to make it more generic and less Neuron-specific. This change allows the function to be accessible from the Core module, particularly after the deserialization process.
> [ISSUE-692] Move Spike History Registration Function to AllVertices for Enhanced Flexibility

- Simulator/Recorders/NG911/Xml911Recorder.cpp
Closes #720 
This pull request addresses an issue caused by merge conflicts in the `Xml911Recorder` class. Removed the definitions of the functions `initDefaultValues()`, `initValues()`, and `getValues()` from `Xml911Recorder.cpp`, which had no corresponding declarations in `Xml911Recorder.h`.
> [ISSUE-720] Remove Unused Functions from Xml911Recorder.cpp

- CMakeLists.txt
Closes #753
I was unable to run ggraphitti with the old CMakeLists configuration. I was able to compile and link, but when the program loaded there was a seg fault. I investigated and there is an external variable, classSynapses_d, that is defined in AllSynapsesDeviceFuncs_d.cpp. Under the old CMakeLists configuration, this file was included in multiple libraries, two of which were linked together. I am not sure how this works.
I changed the source files for the three libraries, edges, vertices, and connections, to only include the necessary sources for each library.  In addition to this change, I made the libraries static. This solved the problem I had, and now ggraphitti loads and runs correctly.
> [ISSUE-753] CMakeLists fixes

- Simulator/Core/CPUModel.cpp
- Simulator/Core/GPUModel.cpp
- Simulator/Core/GPUModel.h
- Simulator/Edges/Neuro/AllSpikingSynapses.cpp
- Simulator/Vertices/AllVertices.h
- Simulator/Vertices/NG911/All911Vertices.cpp
- Simulator/Vertices/NG911/All911Vertices.h
- Simulator/Vertices/Neuro/AllSpikingNeurons.cpp
- Simulator/Vertices/Neuro/AllSpikingNeurons.h
- Simulator/Vertices/Neuro/AllSpikingNeurons_d.cpp
Closes #745 
The summation point logic was being done in the neuron edges for the CPU model while the GPU model had a calcSummationPoint method that handled the GPU-side summation point logic. The feature branch refactors this by introducing a integrateVertexInputs method to AllVertices for both CPU and GPU. The neuron implementation of AllVertices can then implement the summation point logic in this method. This refactor also allows models types other than neuron (such as 911) to define how they want to integration their vertex inputs since not all model types will use summation point logic.
> [issue-745] Refactor where summation is calculated

- Simulator/Core/GPUModel.cpp
- Simulator/Edges/AllEdges.cpp
- Simulator/Edges/AllEdges.h
- Simulator/Edges/NG911/All911Edges.h
- Simulator/Edges/Neuro/AllDSSynapses.h
- Simulator/Edges/Neuro/AllDSSynapses_d.cpp
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses.h
- Simulator/Edges/Neuro/AllDynamicSTDPSynapses_d.cpp
- Simulator/Edges/Neuro/AllSTDPSynapses.h
- Simulator/Edges/Neuro/AllSTDPSynapses_d.cpp
- Simulator/Edges/Neuro/AllSpikingSynapses.h
- Simulator/Edges/Neuro/AllSpikingSynapses_d.cpp
- Simulator/Vertices/AllVertices.cpp
- Simulator/Vertices/AllVertices.h
- Simulator/Vertices/NG911/All911Vertices.h
- Simulator/Vertices/Neuro/AllIFNeurons.h
- Simulator/Vertices/Neuro/AllIFNeurons_d.cpp
- Simulator/Vertices/Neuro/AllIZHNeurons.h
- Simulator/Vertices/Neuro/AllIZHNeurons_d.cpp
Closes #issue838
Refactor all deallocateGPUMemory-related methods to remove parameters, enabling centralized GPU deallocation via OperationManager. This mirrors the existing copyToGPU and copyFromGPU refactors for consistency and streamlined control.
Currently, GPU memory deallocation relies on a chain of responsibility across multiple classes. This change enables centralized control by registering parameterless deallocation functions with the OperationManager.
> Issue 838 deallocate gpu memory
